const NEW_MESSAGE = "NEW_MESSAGE";
const NEW_MESSAGE_ALERT = "NEW_MESSAGE_ALERT";
const NEW_REQUEST = "NEW_REQUEST";

const START_TYPING = "START_TYPING";
const STOP_TYPING = "STOP_TYPING";

const ALERT = "ALERT";
const REFETCH_CHATS = "REFETCH_CHATS";

const ONLINE_USERS = "ONLINE_USERS"

const NEW_USER_CAME = "NEW_USER_CAME"

export {
  NEW_MESSAGE,
  NEW_MESSAGE_ALERT,
  NEW_REQUEST,
  START_TYPING,
  STOP_TYPING,
  ALERT,
  REFETCH_CHATS,
  ONLINE_USERS,
  NEW_USER_CAME
};
